<span style="fontsize:9px;">
<center><h3>Date Stamper Help</h3></center>
<br>
This help file will be updated in the near future.
<br><br>
<strong><u>Technical Details</u></strong><br>
<strong>Development Language:</strong> Python<br>
<strong>Version:</strong> 2.7.3<br>
<strong>Interface Development:</strong> WxWidgets<br>
<strong>Additional Modules:</strong> EXIF<br>
<strong>OS Compatibility:</strong> Windows, Unix, Linux
</span>